# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pavaucha <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/11/07 15:05:06 by pavaucha          #+#    #+#              #
#    Updated: 2017/11/07 17:22:41 by pavaucha         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRC = ft_display_file.c

all: $(NAME)

$(NAME):
	gcc -c $(SRC)
	gcc -o $(NAME) $(SRC)

clean:
	rm -f ft_display_file.o

fclean: clean
	rm -f ft_display_file
